### PR TITLE
ci: linter fixes

### PR DESCRIPTION
**Pull request by konstin**
`cargo test` and `cargo clippy` used to complain.

Tested commands:
```shell
cargo test
cargo test --all-features
cargo clippy
cargo clippy --tests
cargo clippy --tests --all-features
```

### CODE REVIEW

**Review by Eh2406 — APPROVED** [review]
Thank you!

**Comment by Eh2406** [comment]
Can you change the name of the commit so CI is happy?

**Comment by mpizenberg** [comment]
It's not using the PR name because there is a single commit and so it doesn't need squashing?

**Comment by Eh2406** [comment]
Yes.

**Comment by Eh2406** [comment]
Sorry, I didn't notice that you push a fix. Merging now.

**Pull request merged**
