### PR TITLE
ci: remove naming convention ci check

### LINKED ISSUE #218: CI is failing on dev.
We have recently successfully merged PR's that failed "Commit messages follow project guidelines" CI.

1. https://github.com/pubgrub-rs/pubgrub/actions/runs/8914690905/job/24482780384
2. https://github.com/pubgrub-rs/pubgrub/actions/runs/8926571377/job/24517897487
3. https://github.com/pubgrub-rs/pubgrub/actions/runs/8973450833/job/24643647093

We should either give up on this check. Or fix CI (do not let them merge) and reset the dev branch (do not have them in the history) and reemerged the PR's.

### PR DESCRIPTION
**Pull request by konstin**
This change switches pubgrub to commit messages without prefix.

Tagging everyone to sign off before merging.

Closes https://github.com/pubgrub-rs/pubgrub/issues/218

### CODE REVIEW

**Review by mpizenberg — APPROVED** [review]
I don’t have anything against. It was a good guard rail at some point but I’m also ok with not having it.

**Comment by zanieb** [comment]
How is the changelog going to work?

**Comment by konstin** [comment]
We can start using PR labels. Note that we're not really losing anything, the changelog structure is different than the commit labels

**Comment by Eh2406** [comment]
The previous change logs were maintained manually. As no one volunteered to set up tooling that used the conventional commits. Considering approximately everything has changed since the last public release the next logs is going to be hand authored, even if we had tooling set up. So 🤷

**Comment by zanieb** [comment]
Ah if they're not being used for changelog generation than I'm pretty against conventional commit enforcement (but it's not really my project)

**Comment by mpizenberg** [comment]
Indeed, this was introduced by Alex, mainly for commit consistency. Considering the (deliberate) few number of releases, it made more sense to me to craft change logs and release notes manually.

**Review by Eh2406 — APPROVED** [review]
We can insist on this again in the future when someone wants to use tooling to solve release notes being too big/hard. Until then no need.

**Pull request merged**
