### PR TITLE
Prepare the 0.2.1 release

### PR DESCRIPTION
**Pull request by mpizenberg**
Update the lib version and the changelog for the new 0.2.1 version of pubgrub.

### CODE REVIEW

**Comment by mpizenberg** [comment]
Still need to run the benchmarks to update the "?" for the performance improvements numbers. And when this is approved, needs to change the release date.

**Comment by Eh2406** [comment]
Benchmark reslults run on my laptop:

```
Benchmarking large_cases/elm_str_SemanticVersion.ron: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 20.0s. You may wish to increase target time to 127.1s, or reduce sample count to 10.
large_cases/elm_str_SemanticVersion.ron                                                                                 
                        time:   [1.2589 s 1.2597 s 1.2605 s]
Found 6 outliers among 100 measurements (6.00%)
  4 (4.00%) high mild
  2 (2.00%) high severe
large_cases/large_case_u16_NumberVersion.ron
                        change: [+457.86% +458.92% +459.96%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 13 outliers among 100 measurements (13.00%)
  7 (7.00%) high mild
  6 (6.00%) high severe
Benchmarking large_cases/zuse_str_SemanticVersion.ron: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 20.0s. You may wish to increase target time to 277.7s, or reduce sample count to 10.
large_cases/zuse_str_SemanticVersion.ron
                        time:   [2.6835 s 2.6941 s 2.7081 s]
Found 11 outliers among 100 measurements (11.00%)
  1 (1.00%) high mild
  10 (10.00%) high severe
```
and
```
Benchmarking large_cases/elm_str_SemanticVersion.ron: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 20.0s. You may wish to increase target time to 29.2s, or reduce sample count 
to 60.
large_cases/elm_str_SemanticVersion.ron                                                                                 
                        time:   [288.62 ms 288.72 ms 288.84 ms]
                        change: [-77.097% -77.079% -77.063%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
  5 (5.00%) high mild
  3 (3.00%) high severe
Benchmarking large_cases/large_case_u16_NumberVersion.ron: Collecting 100 samples in estimated 20.138 s (1800 iterations
large_cases/large_case_u16_NumberVersion.ron
                        time:   [11.047 ms 11.052 ms 11.057 ms]
                        change: [-80.906% -80.880% -80.856%] (p = 0.00 < 0.05)
                        Performance has improved.
Benchmarking large_cases/zuse_str_SemanticVersion.ron: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 20.0s. You may wish to increase target time to 38.1s, or reduce sample count 
to 50.
large_cases/zuse_str_SemanticVersion.ron                                                                                
                        time:   [369.44 ms 370.04 ms 370.82 ms]
                        change: [-86.339% -86.265% -86.204%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 3 outliers among 100 measurements (3.00%)
  1 (1.00%) high mild
  2 (2.00%) high severe
```

**Comment by mpizenberg** [comment]
Alright I'm getting roughly the same numbers. With improvements ranging from 3x faster to 8x faster depending on the benchmarks. I've updated the numbers in the changelog. Now ready.

**Review by Eh2406 — APPROVED** [review]
Lets give it 8 more days and ship it!

**Comment by Eh2406** [comment]
I don't remember how all the steps to cut a release, but let's make it happen!

**Comment by mpizenberg** [comment]
> I don't remember how all the steps to cut a release, but let's make it happen!

I can do it tonight and add a section in the readme or somewhere else about it :)

**Comment by Eh2406** [comment]
All I remember is that there where lots of things I did not know about that went wrong last time. https://rust-lang.zulipchat.com/#narrow/stream/260232-t-cargo.2FPubGrub/topic/Wrapping.20up.20v0.2E2

**Pull request merged**
