### PR TITLE
Allow `Ranges::contains` to accept borrows, e.g. `&str` for `Ranges<String>`

### PR DESCRIPTION
**Pull request by konstin**
This PR upstreams https://github.com/astral-sh/pubgrub/pull/35.

---

This PR borrows a trick from
[HashMap](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.contains_key) to enable users to pass (e.g.) `&str` to `Ranges::contains`, given `Ranges<String>`.

### CODE REVIEW

**Review by Eh2406 — APPROVED** [review]

**Comment by Eh2406** [comment]
What is our process for releasing a new version of this crate?

**Comment by konstin** [comment]
It's updating `Changelog.md`, bumping the version number and running `cargo publish` locally.

**Comment by Eh2406** [comment]
Two thoughts about this PR.

1.  We should probably add a test, even if it's just to compile test,  for some basic use cases unlocked by this PR.
2.  Do we want hash maps API here? Seems like what we really need is `Q: PartialOrd<V>` not `V: Borrow<Q>`?

**Comment by Eh2406** [comment]
> Do we want hash maps API here? Seems like what we really need is `Q: PartialOrd<V>` not `V: Borrow<Q>`?

`Q: PartialOrd<V>` gets everything compile, and looks quite nice. Unfortunately it doesn't work for 
```
can't compare `str` with `std::string::String`
the trait `PartialOrd<std::string::String>` is not implemented for `str`
the trait `PartialOrd` is implemented for `str`
for that trait implementation, expected `str`, found `std::string::String`
```
So moving on with my life.

**Comment by konstin** [comment]
This works, but i don't know if it's better:

```rust
use std::ops::Deref;

struct Db<V>(Vec<V>);

impl<V> Db<V> {
    pub fn contains<'a, Q, CommonCmp>(&self, version: &'a Q) -> bool
    where
        // We deref both internal and external type to this common type that we use for comparison.
        CommonCmp: PartialOrd<CommonCmp> + ?Sized,
        V: Deref<Target = CommonCmp>,
        &'a Q: Deref<Target = CommonCmp>,
        Q: PartialOrd<CommonCmp> + ?Sized,
    {
        self.0
            .binary_search_by(|segment| segment.deref().partial_cmp(version.deref()).unwrap())
            // An equal interval is one that contains the version
            .is_ok()
    }
}

fn main() {
    let haystack = Db(vec!["1".to_string(), "2".to_string(), "3".to_string()]);
    let one = haystack.contains("1");
    println!("1: {}", one);
    let four = haystack.contains(&"4".to_string());
    println!("4: {}", four);
}
```

**Pull request merged**
