### PR TITLE
More verbose debug assert

### PR DESCRIPTION
**Pull request by konstin**
Accidentally caused this error, added a better debug message

### CODE REVIEW

**Comment by Eh2406** [comment]
Thank you! This looks good. When CI is green I will be happy to merge.

Can you elaborate on how you hit this error? I'm surprised a higher level / user facing check didn't catch the bug.

**Comment by Eh2406** [comment]
(The commit message needs to follow "conventional commit" before I can merge.)

**Comment by mpizenberg** [comment]
> (The commit message needs to follow "conventional commit" before I can merge.)

Nah, it's fine you rename the commit anyway when merging so you can conventionalize it @Eh2406

**Comment by Eh2406** [comment]
@mpizenberg how can I check that the new message will make CI happy. I have messed up before and ended merging with a bad name and had red CI on dev, witch required doing a force push to fix, witch required turning off the branch protection. Witch is a mess I don't want to repeat.

**Comment by mpizenberg** [comment]
Ahah, ok makes sense ^^

**Comment by konstin** [comment]
commitlint passes locally, though i don't know if it matches the CI one.

> Can you elaborate on how you hit this error? I'm surprised a higher level / user facing check didn't catch the bug.

iirc i was midway into refactoring that made more versions available (those with only a source distribution and lacking a wheel) in on place but not in another.

**Review by Eh2406 — APPROVED** [review]
Thank you!

**Pull request merged**
